### ISSUE TITLE
weapon sprite transparency issues part 2

### ISSUE THREAD

**Issue by OmarLego** [hh79/gzdoomvr#45] opened 2021-02-05 17:13 UTC
alright so i just realized now that when i pushed the first message it didnt work because the thing so heres a repost of it, it seems like with some weapon sprites (example shown here is dox778's personalized addon for brutal doom) the transparency of the sprite does some weird wacky shit to other sprites i dont know how to explain it so heres a screenshot, it really bugs me so i hope it gets fixed.
![how2](https://user-images.githubusercontent.com/77136530/107066044-4d9db780-6792-11eb-82ed-edd9ea93ee99.png)

![image](https://user-images.githubusercontent.com/77136530/107065857-17f8ce80-6792-11eb-9128-0ebe8b307478.png)

**Comment by ajantaju** [comment] 2021-02-06 19:27
In this case a video would be more helpful. From the picture i suppose the transparency kind of "blocks" the sprites behind it, rendering them invisible? Also can you provide a link to the mod?

**Comment by OmarLego** [comment] 2021-02-06 22:00
yeah sure thing https://www.moddb.com/mods/brutal-doom/downloads/dox778s-personalized-brutal-doom-v21 this also shows another problem where the crossed sprite doesnt exist for some weapons

https://user-images.githubusercontent.com/77136530/107130570-a39e5800-6883-11eb-81ee-7abf925d6bdd.mp4

**Comment by hh79** [comment] 2021-03-30 10:31
Do you have the latest version 4.5 ? It seems that it could be a duplicate of https://github.com/hh79/gzdoomvr/issues/11

**Comment by WMan22** [comment] 2022-02-23 12:48
> Do you have the latest version 4.5 ? It seems that it could be a duplicate of #11

Actually, that issue is back on 4.7.1 unfortunately.

https://user-images.githubusercontent.com/48204719/155325436-7c6004e8-ee0b-4ee6-bf6d-bcab728b3ebb.mp4

**Comment by hh79** [comment] 2024-12-12 00:36
It will be fixed in the next version

**Comment by hh79** [comment] 2024-12-14 13:12
Fixed in https://github.com/hh79/gzdoomvr/commit/756c03c736f06fd12bf1d2d739e0378f77b2ae0c

**Closed as completed by hh79** 2024-12-14 13:12 UTC
Labels: bug
